const dummyData = {
    categories: [
        { name: "Burgers", description: "Succulent flame-grilled burgers" },
        { name: "Pizzas", description: "Wood-fired cheesy pizzas" },
        { name: "Burritos", description: "Wrapped Mexican favorites" },
        { name: "Sandwiches", description: "Layered and loaded sandwiches" },
        { name: "Wraps", description: "Flavor-packed rolled wraps" },
        { name: "Poke Bowls", description: "Fresh rice and protein bowls" },
    ],

    customizations: [
        // Toppings
        { name: "Extra Cheese", price: 20, type: "topping" },
        { name: "Jalapeños", price: 15, type: "topping" },
        { name: "Onions", price: 10, type: "topping" },
        { name: "Olives", price: 20, type: "topping" },
        { name: "Mushrooms", price: 18, type: "topping" },
        { name: "Tomatoes", price: 13, type: "topping" },
        { name: "Lettuce", price: 10, type: "topping" },
        { name: "Bacon", price: 34, type: "topping" },
        { name: "Avocado", price: 40, type: "topping" },

        // Sides
        { name: "Coke", price: 25, type: "side" },
        { name: "Fries", price: 40, type: "side" },
        { name: "Garlic Bread", price: 50, type: "side" },
        { name: "Chicken Nuggets", price: 52, type: "side" },
        { name: "Iced Tea", price: 25, type: "side" },
        { name: "Salad", price: 30, type: "side" },
        { name: "Potato Wedges", price: 32, type: "side" },
        { name: "Mozzarella Sticks", price: 40, type: "side" },
        { name: "Sweet Corn", price: 32, type: "side" },
        { name: "Choco Lava Cake", price: 50, type: "side" },
    ],

    menu: [
        {
            name: "Original Cheeseburger",
            description: "Juicy beef patty with melted cheese and fresh veggies",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/044/844/600/large_2x/homemade-fresh-tasty-burger-with-meat-and-cheese-classic-cheese-burger-and-vegetable-ai-generated-free-png.png",
            price: 26.99,
            rating: 4.8,
            calories: 500,
            protein: 25,
            category_name: "Burgers",
            customizations: ["Extra Cheese", "Coke", "Fries", "Onions", "Bacon", "Lettuce"],
        },
        {
            name: "Pepperoni Deluxe",
            description: "Crispy crust topped with premium pepperoni and mozzarella",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/023/742/417/large_2x/pepperoni-pizza-isolated-illustration-ai-generative-free-png.png",
            price: 31.99,
            rating: 4.8,
            calories: 750,
            protein: 36,
            category_name: "Pizzas",
            customizations: [
                "Extra Cheese",
                "Jalapeños",
                "Garlic Bread",
                "Coke",
                "Olives",
            ],
        },
        {
            name: "Hearty Bean Burrito",
            description: "Warm tortilla filled with seasoned beans and fresh salsa",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/055/133/581/large_2x/deliciously-grilled-burritos-filled-with-beans-corn-and-fresh-vegetables-served-with-lime-wedge-and-cilantro-isolated-on-transparent-background-free-png.png",
            price: 19.99,
            rating: 4.3,
            calories: 460,
            protein: 20,
            category_name: "Burritos",
            customizations: ["Jalapeños", "Iced Tea", "Fries", "Salad"],
        },
        {
            name: "Smoky BBQ Burger",
            description: "Flame-grilled patty with tangy BBQ glaze and crispy bacon",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/060/236/245/large_2x/a-large-hamburger-with-cheese-onions-and-lettuce-free-png.png",
            price: 23.5,
            rating: 4.6,
            calories: 600,
            protein: 28,
            category_name: "Burgers",
            customizations: ["Onions", "Fries", "Coke", "Bacon", "Avocado"],
        },
        {
            name: "Caesar Chicken Roll",
            description: "Tender grilled chicken wrapped with crisp romaine and Caesar",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/048/930/603/large_2x/caesar-wrap-grilled-chicken-isolated-on-transparent-background-free-png.png",
            price: 22.99,
            rating: 4.5,
            calories: 490,
            protein: 30,
            category_name: "Wraps",
            customizations: ["Extra Cheese", "Coke", "Potato Wedges", "Tomatoes"],
        },
        {
            name: "Roasted Veggie Delight",
            description: "Garden vegetables with basil pesto on toasted bread",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/047/832/012/large_2x/grilled-sesame-seed-bread-veggie-sandwich-with-tomato-and-onion-free-png.png",
            price: 20.5,
            rating: 4,
            calories: 440,
            protein: 19,
            category_name: "Sandwiches",
            customizations: ["Mushrooms", "Olives", "Mozzarella Sticks", "Iced Tea"],
        },
        {
            name: "Ultimate Double Stack",
            description: "Two savory beef patties stacked with melted cheddar",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/060/359/627/large_2x/double-cheeseburger-with-lettuce-tomatoes-cheese-and-sesame-bun-free-png.png",
            price: 32.99,
            rating: 4.9,
            calories: 720,
            protein: 35,
            category_name: "Burgers",
            customizations: [
                "Extra Cheese",
                "Onions",
                "Fries",
                "Coke",
                "Chicken Nuggets",
            ],
        },
        {
            name: "Tandoori Paneer Wrap",
            description: "Marinated paneer with cooling mint sauce and crunchy veggies",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/057/913/530/large_2x/delicious-wraps-a-tantalizing-array-of-wraps-filled-with-vibrant-vegetables-succulent-fillings-and-fresh-ingredients-artfully-arranged-for-a-mouthwatering-culinary-experience-free-png.png",
            price: 19.99,
            rating: 4.4,
            calories: 420,
            protein: 20,
            category_name: "Wraps",
            customizations: ["Jalapeños", "Tomatoes", "Salad", "Fries", "Iced Tea"],
        },
        {
            name: "Fiesta Burrito Bowl",
            description: "Cilantro rice layered with black beans and fresh guacamole",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/057/466/374/large_2x/healthy-quinoa-bowl-with-avocado-tomato-and-black-beans-ingredients-free-png.png",
            price: 27.59,
            rating: 4.8,
            calories: 650,
            protein: 25,
            category_name: "Bowls",
            customizations: ["Avocado", "Sweet Corn", "Salad", "Iced Tea"],
        },
        {
            name: "Nashville Hot Chicken",
            description: "Buttermilk fried chicken with fiery hot sauce and pickles",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/051/814/008/large_2x/a-grilled-chicken-sandwich-with-lettuce-and-tomatoes-free-png.png",
            price: 25,
            rating: 4.4,
            calories: 600,
            protein: 30,
            category_name: "Sandwiches",
            customizations: [
                "Jalapeños",
                "Onions",
                "Fries",
                "Coke",
                "Choco Lava Cake",
            ],
        },
        {
            name: "Traditional Margherita",
            description: "San Marzano tomatoes with buffalo mozzarella and basil",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/058/700/845/large_2x/free-isolated-on-transparent-background-delicious-pizza-topped-with-fresh-tomatoes-basil-and-melted-cheese-perfect-for-food-free-png.png",
            price: 23.99,
            rating: 4.2,
            calories: 580,
            protein: 26,
            category_name: "Pizzas",
            customizations: ["Extra Cheese", "Olives", "Coke", "Garlic Bread"],
        },
        {
            name: "Fitness Fuel Bowl",
            description: "Herb-marinated chicken over protein-rich quinoa blend",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/056/106/379/large_2x/top-view-salad-with-chicken-avocado-tomatoes-and-lettuce-free-png.png",
            price: 30,
            rating: 4.7,
            calories: 610,
            protein: 40,
            category_name: "Bowls",
            customizations: ["Avocado", "Salad", "Sweet Corn", "Iced Tea"],
        },
        {
            name: "Spiced Paneer Burrito",
            description: "Cottage cheese in aromatic masala with basmati rice",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/056/565/254/large_2x/burrito-with-cauliflower-and-vegetables-free-png.png",
            price: 21,
            rating: 4.3,
            calories: 530,
            protein: 25,
            category_name: "Burritos",
            customizations: ["Jalapeños", "Fries", "Garlic Bread", "Coke"],
        },
        {
            name: "Triple Decker Club",
            description: "Layered chicken breast with crispy bacon and garden greens",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/060/364/135/large_2x/a-flavorful-club-sandwich-with-turkey-bacon-and-fresh-vegetables-sliced-and-isolated-on-a-transparent-background-free-png.png",
            price: 23.5,
            rating: 4.6,
            calories: 590,
            protein: 32,
            category_name: "Sandwiches",
            customizations: ["Bacon", "Tomatoes", "Lettuce", "Mozzarella Sticks", "Iced Tea"],
        },
    ],
};

export default dummyData;